name: Deploy Wisecow App to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Wisecow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: smusthaf20
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t smusthaf20/wisecow-app:latest .
        docker push smusthaf20/wisecow-app:latest

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config

    - name: Verify cluster access
      run: kubectl get nodes

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/
