name: Deploy to Minikube

on:
  push:
    branches:
      - main  # or any branch you deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubeconfig for Minikube
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.MINIKUBE_KUBECONFIG }}" | base64 -d > ~/.kube/config

    - name: Check cluster connectivity
      run: kubectl get pods -A

    # Optional: Deploy your app
    - name: Deploy manifests
      run: |
        kubectl apply -f k8s/  # Adjust path to your manifest folder
